spring:
  application:
    name: AccountBook
  datasource:
    url: jdbc:mysql://localhost:3306/AccountBook
    username: root
    password: 0dong2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.infinispan.InfinispanRegionFactory
          infinispan:
            cfg: infinispan.xml
            statistics: true
        generate_statistics: true

logging:
  level:
    com.hazelcast: DEBUG
    org.hibernate:
      SQL: DEBUG
