spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AccountBook
    username: root
    password: 0dong2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
        format_sql: true

logging:
  level:
    org.hibernate:
      SQL: DEBUG
